### ISSUE TITLE
General Feedback on Proposal

### ISSUE THREAD

**Issue by akingabramson** [tonywon89/feed_my_curiosity#1]
Overall, looks good!  The main change I would make: the frontend is going to take longer than you think.  Style the signup/login pages as soon as they work so you can hit CSS bugs while TAs are still around to help. You want to build one individual feature at a time, if possible. 

Once you're done with auth, start feeds and code the full stack for it (from migrations to react routing to views to CSS).  Then move on to sidebar, etc.

**Comment by tonywon89** [comment]
Got it thank you!
